name: Setup Kubernetes Credentials
description: Get Secret
inputs:
  kube_config:
    description: 'Kube config secret as base64 string'
    required: false
  
runs:
  using: composite
  steps:
    - name: "Provide credentials"
      if: inputs.kube_config != ''
      shell: bash
      run: |
          mkdir -p ~/.kube/
          echo -n "${{inputs.kube_config}}" | base64 -d  > ~/.kube/config
          chmod 600 ~/.kube/config
          mysize=$(find "$HOME/.kube/config" -printf "%s")
          if [ $mysize -lt 100 ]; then
            echo "Kube config is too small"
            exit 1
          fi