name: Helm Deploy
description: Deploy a chart through Helm

inputs: 
  namespace:
    description: 'Namespace to diff'
    required: true
  
  chart:
    description: 'Chart to deploy'
    required: true
  
  kube_config:
    description: 'Kube config secret as base64 string'
    required: true

  repo_name:
    description: 'Name of the Helm repo'
    required: false
    default: forestsoft
  
  repo:
    description: 'URL to repo'
    required: false
    default: 'https://Forestsoft-de.github.io/helm-charts/charts'
  
  release_name:
    description: 'Name of the release'
    required: true

  tag:
    required: true
    description: 'Image tag to use'
  
  values:
    description: 'Path to Values to use'
    required: true

  image_tag:
    description: 'Image tag to use'
    required: true

  dry_run:
    description: 'Dry run'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: ForestsoftGmbH/gh-deploy-action/actions/helm-diff@main
      name: Validate Helm Chart
      with:
        namespace: ${{ inputs.namespace }}
        chart: forestsoft/forestsoft-helm-lamp
        release_name: ${{ inputs.release_name }}
        values: "build/charts/values.yaml -f build/charts/${{ inputs.environment }}-values.yaml"
        image_tag: ${{ inputs.tag }}
        kube_config: ${{ inputs.kube_config }}

    - uses: ForestsoftGmbH/gh-deploy-action/actions/helm-repo@main
      if: inputs.repo != ''
      with:
        repo_name: ${{ inputs.repo_name }}
        repo: ${{ inputs.repo }}
    
    - name: "Helm Deploy"
      if: inputs.dry_run == 'false'
      shell: bash
      env:
        TERM: xterm-color
        HELM_DIFF_COLOR: "true"
      run: |
        helm upgrade --install --namespace ${{ inputs.namespace }} -f ${{ inputs.values }} --set image.tag=${{inputs.image_tag}} ${{ inputs.release_name }} ${{ inputs.chart }}
        
       
