name: Helm Deploy
description: Deploy a chart through Helm

inputs: 
  namespace:
    description: 'Namespace to diff'
    required: true
  
  chart:
    description: 'Chart to deploy'
    required: true
  
  kube_config:
    description: 'Kube config secret as base64 string'
    required: true

  repo_name:
    description: 'Name of the Helm repo'
    required: false
    default: forestsoft
  
  repo:
    description: 'URL to repo'
    required: false
    default: 'https://forestsoftgmbh.github.io/helm-charts/charts'
  
  release_name:
    description: 'Name of the release'
    required: true
 
  values:
    description: 'Path to Values to use'
    default: ''
    required: false

  debug:
    description: 'Debug Helm Chart'
    required: false
    default: 'false'

  wait:
    description: 'Wait for resources to be ready'
    required: false
    default: 'true'

  timeout:
    description: 'Timeout for wait'
    required: false
    default: '5m'
  
  atomic:
    description: 'Perform atomic upgrade'
    required: false
    default: 'false'
  
  image_tag:
    description: 'Image tag to use'
    default: ''
    required: false
  
  database_image_tag:
    description: 'Database Image tag to use'
    default: ''
    required: false

  force:
    description: 'Force upgrade'
    required: false
    default: 'false'

  test_release:
    description: 'Run Helm tests after release'
    required: false
    default: 'false'
  
  version:
    description: 'Chart Version to use'
    required: false
    default: ''
  
  diff:
    description: 'Number of lines to show in diff'
    required: false
    default: 'true'
  
  history_max:
    description: 'Keep at most this many history entries'
    required: false
    default: "2"
  
  diff_lines:
    description: 'Number of lines to show in diff'
    required: false
    default: "10"
  
  dry_run:
    description: 'Dry run'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - uses: ForestsoftGmbH/gh-deploy-action/.github/actions/helm-repo@main
      if: inputs.repo != ''
      with:
        repo_name: ${{ inputs.repo_name }}
        repo: ${{ inputs.repo }}
    - uses: ForestsoftGmbH/gh-deploy-action/.github/actions/helm-dependency-update@main
      with:
        chart: ${{ inputs.chart }}
    
    - name: "Build Opts"
      shell: bash
      id: optbuilder
      env:
        TERM: xterm-color
        HELM_DIFF_COLOR: "true"
      run: |
        OPTS=""
        if [ "${{ inputs.wait }}" == "true" ]; then
          OPTS="$OPTS --wait"
        fi
        if [ "${{ inputs.timeout }}" != "" ]; then
          OPTS="$OPTS --timeout ${{ inputs.timeout }}"
        fi
        if [ "${{ inputs.atomic }}" == "true" ]; then
          OPTS="$OPTS --atomic"
        fi
        if [ "${{ inputs.version }}" != "" ]; then
          OPTS="$OPTS --version ${{ inputs.version }}"
        fi
        if [ "${{ inputs.force }}" == "true" ]; then
          OPTS="$OPTS --force"
        fi
        if [ "${{inputs.values}}" != "" ]; then
          OPTS="$OPTS -f ${{inputs.values}}"
        fi
        if [ "${{inputs.image_tag}}" != "" ]; then
          OPTS="$OPTS  --set image.tag=${{inputs.image_tag}}"
        fi
        if [ "${{inputs.database_image_tag}}" != "" ]; then
          OPTS="$OPTS  --set database.image.tag=${{inputs.database_image_tag}}"
        elif [ "${{inputs.image_tag}}" != "" ]; then
          OPTS="$OPTS  --set database.image.tag=${{inputs.image_tag}}"
        fi
        echo "opts=$OPTS" >> $GITHUB_OUTPUT

    - uses: ForestsoftGmbH/gh-deploy-action/.github/actions/helm-diff@main
      name: Validate Helm Chart
      if: inputs.diff == 'true' && inputs.debug == 'false'
      with:
        namespace: ${{ inputs.namespace }}
        chart: ${{ inputs.chart }}
        release_name: ${{ inputs.release_name }}
        version: ${{ inputs.version }}
        repo: ${{ inputs.repo }}
        values: ${{ inputs.values }}
        image_tag: ${{ inputs.image_tag }}
        database_image_tag: ${{ inputs.database_image_tag }}
        diff_lines: ${{ inputs.diff_lines }}
        kube_config: ${{ inputs.kube_config }}
    
    - uses: ForestsoftGmbH/gh-deploy-action/.github/actions/helm-dry-run@main
      name: Dry Run Helm Chart
      if: inputs.dry_run == 'true' && inputs.debug == 'false'
      with:
        namespace: ${{ inputs.namespace }}
        chart: ${{ inputs.chart }}
        repo: ${{ inputs.repo }}
        release_name: ${{ inputs.release_name }}
        values: ${{ inputs.values }}
        version: ${{ inputs.version }}
        image_tag: ${{ inputs.image_tag }}
        database_image_tag: ${{ inputs.database_image_tag }}
        kube_config: ${{ inputs.kube_config }}
    
    - uses: ForestsoftGmbH/gh-deploy-action/.github/actions/kube-credentials@main
      if: inputs.dry_run == 'false'
      with:
        kube_config: ${{ inputs.kube_config }}
    
    - name: "Helm Template Debug"
      if: inputs.debug == 'true'
      shell: bash
      env:
        TERM: xterm-color
        HELM_DIFF_COLOR: "true"
      run: |
        helm template --debug ${{steps.optbuilder.outputs.opts}} ${{ inputs.release_name }} ${{ inputs.chart }}

    - name: "Helm Deploy"
      if: inputs.dry_run == 'false' && inputs.debug == 'false'
      shell: bash
      env:
        TERM: xterm-color
        HELM_DIFF_COLOR: "true"
      run: |
        helm upgrade --install --history-max=${{ inputs.history_max }} --namespace ${{ inputs.namespace }} ${{steps.optbuilder.outputs.opts}} ${{ inputs.release_name }} ${{ inputs.chart }}
    - name: "Test release"        
      shell: bash
      if: inputs.test_release == 'true' && inputs.dry_run == 'false'
      env:
        TERM: xterm-color
        HELM_DIFF_COLOR: "true"
      run: |
        helm test --namespace ${{ inputs.namespace }} ${{ inputs.release_name }}
       
