name: Helm Repo
description: 'Add Helm Repo'
inputs:
  repo_name:
    description: 'Name of the Helm repo'
    required: false
    default: forestsoft
  repo:
    description: 'URL to repo'
    required: false
    default: 'https://forestsoftgmbh.github.io/helm-charts/charts'

runs:
  using: "composite"
  steps:
    - name: "Add Helm Repo"
      shell: bash
      run: |
        helm repo add ${{ inputs.repo_name }} ${{ inputs.repo }}
        helm repo update
