name: Helm Diff
description: Diff Template in a namespace

inputs: 
  
  namespace:
    description: 'Namespace to diff'
    required: true
  
  chart:
    description: 'Chart to deploy'
    required: true
  
  kube_config:
    description: 'Kube config secret as base64 string'
    required: true

  repo_name:
    description: 'Name of the Helm repo'
    required: false
    default: forestsoft
  
  diff_lines:
    description: 'Number of lines to show in diff'
    required: false
    default: ""
  
  repo:
    description: 'URL to repo'
    required: false
    default: 'https://forestsoftgmbh.github.io/helm-charts/charts'
  
  release_name:
    description: 'Name of the release'
    required: true

  values:
    description: 'Path to Values to use'
    required: true

  image_tag:
    description: 'Image tag to use'
    required: false

runs:
  using: "composite"
  steps:
    - uses: ForestsoftGmbH/gh-deploy-action/.github/actions/kube-credentials@main
      with:
        kube_config: ${{ inputs.kube_config }}
    - uses: ForestsoftGmbH/gh-deploy-action/.github/actions/helm-repo@main
      if: inputs.repo != ''
      with:
        repo_name: ${{ inputs.repo_name }}
        repo: ${{ inputs.repo }}
    - name: "Helm Intall Plugin"
      shell: bash
      run: |
        helm plugin install https://github.com/databus23/helm-diff > /dev/null || true
    - name: "Helm Diff"
      shell: bash
      env:
        TERM: xterm-color
        HELM_DIFF_COLOR: "true"
      run: |
        OPTS="--allow-unreleased"
        if [ "${{inputs.diff_lines}}" != "" ]; then
          OPTS="$OPTS -C ${{inputs.diff_lines}}"
        fi
        if [ "${{inputs.image_tag}}" != "" ]; then
          helm diff upgrade $OPTS --namespace ${{ inputs.namespace }} -f ${{ inputs.values }} --set image.tag=${{inputs.image_tag}} --set database.image.tag=${{inputs.image_tag}} ${{ inputs.release_name }} ${{ inputs.chart }}
        else 
          helm diff upgrade $OPTS --namespace ${{ inputs.namespace }} -f ${{ inputs.values }} ${{ inputs.release_name }} ${{ inputs.chart }}
        fi
       
