name: Helm Diff
description: Diff Template in a namespace

inputs: 
  
  namespace:
    description: 'Namespace to diff'
    required: true
  
  chart:
    description: 'Chart to deploy'
    required: true
  
  kube_config:
    description: 'Kube config secret as base64 string'
    required: true

  repo_name:
    description: 'Name of the Helm repo'
    required: false
    default: forestsoft
  
  repo:
    description: 'URL to repo'
    required: false
    default: 'https://Forestsoft-de.github.io/helm-charts/charts'
  
  release_name:
    description: 'Name of the release'
    required: true

  values:
    description: 'Path to Values to use'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/kube-credentials
      with:
        kube_config: ${{ inputs.kube_config }}
    - uses: ./.github/actions/helm-repo
      with:
        repo_name: ${{ inputs.repo_name }}
        repo: ${{ inputs.repo }}
    - name: "Helm diff"
      shell: bash
      run: |
        helm plugin install https://github.com/databus23/helm-diff
        helm diff --namespace ${{ inputs.namespace }} -f ${{ inputs.values }} --debug ${{ inputs.release_name }} ${{ inputs.chart }}
        
       
