name: Autmatic Version
description: Use this action to automatically increase the version of your project

inputs:
  tag_version:
    description: 'Tag version'
    required: false
    default: 'true'
outputs:
  version:
    description: 'The new version'
    value: ${{ steps.get_next_version.outputs.version }}
  isNewVersion:
    description: 'True if the version has been increased'
    value: ${{ steps.get_next_version.outputs.hasNextVersion }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Get next version
      id: get_next_version
      uses: docker://forestsoft/get-next-version
      with:
        entrypoint: /action/entrypoint.sh
    - name: Show the next version
      shell: bash
      id: version
      run: |
        echo ${{ steps.get_next_version.outputs.version }}
        echo ${{ steps.get_next_version.outputs.hasNextVersion }}
    - name: Tag version
      if: inputs.tag_version == 'true' && steps.get_next_version.outputs.hasNextVersion == 'true'
      shell: bash
      run: |
        git config --global user.email ""    
        git config --global user.name "GitHub Action"
        git tag ${{ steps.get_next_version.outputs.version }}
        git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git --follow-tags
        git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git --tags
        

       
